// Generated by CoffeeScript 1.8.0
(function() {
  this.customMatchers = {
    toBeInstanceOf: function(util, customEqualityTesters) {
      return {
        compare: function(actual, expected) {
          return {
            pass: actual instanceof expected
          };
        }
      };
    }
  };

}).call(this);
